use crate::deck::CardListItem;

pub fn build_blakes_example_deck() -> Vec<CardListItem>{
	vec![
		CardListItem("Neyali, Suns' Vanguard".to_string(), 1),
		CardListItem("Idol of Oblivion".to_string(), 1),
		CardListItem("Temple of the False God".to_string(), 1),
		CardListItem("Castle Ardenvale".to_string(), 1),
		CardListItem("Elspeth Tirel".to_string(), 1),
		CardListItem("Path to Exile".to_string(), 1),
		CardListItem("Martial Coup".to_string(), 1),
		CardListItem("Increasing Devotion".to_string(), 1),
		CardListItem("Boros Garrison".to_string(), 1),
		CardListItem("Soul-Guide Lantern".to_string(), 1),
		CardListItem("Phantom General".to_string(), 1),
		CardListItem("Flawless Maneuver".to_string(), 1),
		CardListItem("Jor Kadeen, the Prevailer".to_string(), 1),
		CardListItem("Commander's Sphere".to_string(), 1),
		CardListItem("Mace of the Valiant".to_string(), 1),
		CardListItem("Loyal Apprentice".to_string(), 1),
		CardListItem("Battle Screech".to_string(), 1),
		CardListItem("Goldwardens' Gambit".to_string(), 1),
		CardListItem("Maul of the Skyclaves".to_string(), 1),
		CardListItem("Midnight Haunting".to_string(), 1),
		CardListItem("Hour of Reckoning".to_string(), 1),
		CardListItem("Emeria Angel".to_string(), 1),
		CardListItem("Finale of Glory".to_string(), 1),
		CardListItem("Boros Signet".to_string(), 1),
		CardListItem("Myr Battlesphere".to_string(), 1),
		CardListItem("Prava of the Steel Legion".to_string(), 1),
		CardListItem("Command Tower".to_string(), 1),
		CardListItem("Castle Embereth".to_string(), 1),
		CardListItem("Otharri, Suns' Glory".to_string(), 1),
		CardListItem("Arcane Signet".to_string(), 1),
		CardListItem("Solemn Simulacrum".to_string(), 1),
		CardListItem("Assemble the Legion".to_string(), 1),
		CardListItem("Intangible Virtue".to_string(), 1),
		CardListItem("Cut a Deal".to_string(), 1),
		CardListItem("Mind Stone".to_string(), 1),
		CardListItem("Legion Warboss".to_string(), 1),
		CardListItem("Mask of Memory".to_string(), 1),
		CardListItem("Call the Coppercoats".to_string(), 1),
		CardListItem("Heroic Reinforcements".to_string(), 1),
		CardListItem("Exotic Orchard".to_string(), 1),
		CardListItem("Mentor of the Meek".to_string(), 1),
		CardListItem("Clever Concealment".to_string(), 1),
		CardListItem("Siege-Gang Commander".to_string(), 1),
		CardListItem("Kemba's Banner".to_string(), 1),
		CardListItem("Path of Ancestry".to_string(), 1),
		CardListItem("Roar of Resistance".to_string(), 1),
		CardListItem("Sol Ring".to_string(), 1),
		CardListItem("Kher Keep".to_string(), 1),
		CardListItem("Felidar Retreat".to_string(), 1),
		CardListItem("Collective Effort".to_string(), 1),
		CardListItem("Court of Grace".to_string(), 1),
		CardListItem("Temple of Triumph".to_string(), 1),
		CardListItem("Chain Reaction".to_string(), 1),
		CardListItem("Buried Ruin".to_string(), 1),
		CardListItem("Glimmer Lens".to_string(), 1),
		CardListItem("White Sun's Zenith".to_string(), 1),
		CardListItem("Windbrisk Heights".to_string(), 1),
		CardListItem("Slayers' Stronghold".to_string(), 1),
		CardListItem("Silverwing Squadron".to_string(), 1),
		CardListItem("Harmonious Archon".to_string(), 1),
		CardListItem("Adriana, Captain of the Guard".to_string(), 1),
		CardListItem("Forgotten Cave".to_string(), 1),
		CardListItem("Fellwar Stone".to_string(), 1),
		CardListItem("Rip Apart".to_string(), 1),
		CardListItem("Goldnight Commander".to_string(), 1),
		CardListItem("Hexplate Wallbreaker".to_string(), 1),
		CardListItem("Boros Charm".to_string(), 1),
		CardListItem("Generous Gift".to_string(), 1),
		CardListItem("Hordeling Outburst".to_string(), 1),
		CardListItem("Myriad Landscape".to_string(), 1),
		CardListItem("Hate Mirage".to_string(), 1),
		CardListItem("Loxodon Warhammer".to_string(), 1),
		CardListItem("Secluded Steppe".to_string(), 1),
		CardListItem("Furycalm Snarl".to_string(), 1),
		CardListItem("Staff of the Storyteller".to_string(), 1),
		CardListItem("Dragonmaster Outcast".to_string(), 1),
		CardListItem("Vulshok Factory".to_string(), 1),
		CardListItem("Talisman of Conviction".to_string(), 1),
		CardListItem("Plains".to_string(), 11),
		CardListItem("Mountain".to_string(), 11),
	]
}